version: "3.9"

services:
  ecom_with_agent_api:
    build:
      context: .
      args:
        - Dev=true
    ports:
      - "8000:8000"
    volumes:
      - ./ecomWithAgentApi:/ecomWithAgentApi
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 subscriptionproject.wsgi:application"

    environment:
      - DB_HOST = databse
      - DB_NAME = userdb
      - DB_USER = userone
      - DB_PASS = pass1234
    depends_on:
      - database


  database:
    image: postgres
    volumes:
      - dev-db:var/lib/postgres/data
    environment:
      - POSTGRES_DB = userdb
      - POSTGRES_USER = userone
      - POSTGRES_PASSWORD = pass1234

volumes:
  dev-db: