version: "3.9"

services:
  ecomWithAgentApi:
    build:
      context: .
      args:
        - Dev=true
    ports:
      - "8000:8000"
    volumes:
      - ./ecomWithAgentApi:/ecomWithAgentApi
    command: >
      sh -c "gunicorn --bind 0.0.0.0:8000 subscriptionproject.wsgi:application"