version: "3.9"

services:
  ecomWithAgentApi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./ecomWithAgentApi:/ecomWithAgentApi
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"